### ISSUE TITLE
utf8mb4_bin usage

### ISSUE THREAD

**Issue by fritzmg** [contao/newsletter-bundle#13]
As already mentioned in https://github.com/contao/comments-bundle/issues/13 the newsletter-bundle for version 4.5.0 only required the core-bundle in version ^4.4. Thus the 4.5.0 version of this bundle is also automatically installed in Contao 4.4 installations (when using a default composer.json).

This has been fixed in 4279e576cfccd88840f6eee76e647cd3d9e1314e. However since there is already a `4.5.0` release of this bundle without this change, the `4.5.0` release will still be installed in Contao 4.4. This is a problem, since version `4.5.0` of this bundle uses `utf8mb4_bin` [here](https://github.com/contao/newsletter-bundle/blob/4.5.0/src/Resources/contao/dca/tl_newsletter.php#L153) - and proper utf8mb4 support (plus requirement checks) have only been added in Contao 4.5.0 (see also https://github.com/contao/comments-bundle/issues/13#issuecomment-354671141).

Not sure how this should be fixed though.

**Comment by leofeyer** [comment]
The only way to fix this is to remove the `4.5.0` tag of the comments, listing and newsletter bundles. I am going to do this as soon as I have tagged version 4.5.1.

**Comment by aschempp** [comment]
Fine with me

**Comment by leofeyer** [comment]
Done.

**Comment by fritzmg** [comment]
Btw. why do all the `alias` fields use a hardcoded `utf8mb4_bin` collation now anyway? Even if you set
```yml
doctrine:
    dbal:
        connections:
            default:
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
```
the collation of these fields would still be `utf8mb4_bin`.
